# Generated by Django 4.1.4 on 2022-12-30 10:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedbacker', models.CharField(default='DEFAULT', max_length=30)),
                ('feedbacker_userid', models.CharField(default='DEFAULT', max_length=30)),
                ('feedbacker_email', models.EmailField(default='none@gmail.com', max_length=100)),
                ('feedback', models.CharField(default='NO FEEDBACK', max_length=600)),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='CLIP', max_length=100)),
                ('video', models.FileField(default='DEFAULT_MODEL', upload_to='videos/')),
            ],
        ),
    ]
